pool: 
  vmImage: 'ubuntu-latest'
stages:
- stage: DockerTest
  jobs:
  - job:
    strategy:
      matrix:
        'Splunk 8.1':
          splunk_docker_image: 'splunk/splunk:8.1'
        'Splunk 8.2':
          splunk_docker_image: 'splunk/splunk:8.2'
        'Splunk 9.0':
          splunk_docker_image: 'splunk/splunk:9.0'
    steps:
      - checkout: self 
      - task: Cache@2
        displayName: Cache Powershell Modules
        inputs:
          key: Invoke-Build-Ubuntu
          path: /home/vsts/.local/share/powershell/Modules/InvokeBuild
          cacheHitVar: InvokeBuildIsCached
      - task: PowerShell@2
        displayName: 'Download Powershell Modules'
        condition: ne(variables.InvokeBuildIsCached,'true')
        inputs:
          pwsh: true
          targetType: inline
          script: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module InvokeBuild -ErrorAction Stop
      - task: PowerShell@2
        displayName: 'Run Docker Test'
        inputs:
          pwsh: true
          targetType: inline
          script: |
            cd ./test/docker
            Invoke-Build -Task RunDockerIntegrationTest -SplunkDockerImage "$(splunk_docker_image)"